eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/zhoujie19940715/config-repo
          search-paths: spring-cloud-config
          username: zhoujie19940715
          password: Jj839291
          basedir: E:/projects/springCloud_imooc/cloudmall/config/basedir
  #需要用到springCloudBus
#  rabbitmq:
#    host: 192.168.4.94
#    port: 5672
#    username: guest
#    password: guest
##将接口暴露出来
#management:
#  endpoints:
#    web:
#      exposure:
#        include: bus-refresh
#debug: false


