eureka:
  client:
    service-url:
     defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: api-gateway
  cloud:
#    config:
#      discovery:
#        enabled: true
#        service-id: config-server
#      profile: dev
#      label: master

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
zuul:
  routes:
    myProduct:
      path: /myProduct/**
      serviceId: product
      #不过滤cookie
      sensitiveHeaders: